# Generated by Django 5.0.1 on 2024-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0002_loginhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
