# Generated by Django 5.0.1 on 2024-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_account", "0004_user_country_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginhistory",
            options={
                "ordering": ("-login_date",),
                "verbose_name": "LoginHistory",
                "verbose_name_plural": "LoginHistories",
            },
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="login_method",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="loginhistory",
            table="user_login_history",
        ),
    ]
